version: "3.8"

services:
  postgres:
    container_name: api_postgesql
    image: postgres:13
    ports:
      - "5832:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=book_db

volumes:
  db_data:
